[package]
name = "editor"
version = "0.1.0"
authors = ["Ryan Sadler <rrsadler@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ropey = "1.2.0"
termion = "1.5.5"
unicode-segmentation = "1.7.1"
clap = "2.33.0"
