[package]
name = "editor"
version = "0.1.0"
authors = ["Ryan Sadler <rrsadler@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ropey = "1.2.0"
termion = "1.5.5"
crossterm = "0.19.0"
unicode-segmentation = "1.7.1"
clap = "2.33.0"
stderrlog = "0.5"
log = "0.4"
nom = "6.0.1"
combine = "4.3.2"
gamma = "0.8"
petgraph = "0.5.1"
pretty_env_logger = "0.4"

[[bin]]
name = "bindings"
path = "src/bindings/main.rs"



